### ISSUE TITLE
Infinite API call loop

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1393] opened 2020-01-15 16:55 UTC
### Describe the problem and steps to reproduce it:

1. Navigate to https://code.addons-dev.allizom.org/en-US/browse/502955/versions/1541798/
2. Open the network panel

### What happened?

Lots of API calls are made.

### What did you expect to happen?

Not that.

### Anything else we should know?

After some time, it breaks my FF tab. It also breaks the CodeOverview (maybe?) and it makes it hard to navigate to other files.

**Comment by willdurand** [comment] 2020-01-15 16:55
It affects both the "browse" and "compare" pages: https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541786...1541798/

**Comment by mirefly** [comment] 2020-01-15 17:33
Addons-server landed the patch (https://github.com/mozilla/addons-server/pull/13237) to allow null sha256 for files except the selected file, and the following logic makes the component cannot get the version file from redux store.

https://github.com/mozilla/addons-code-manager/blob/ee7d455dbe30a6796387f6b284548a0c0c2716d2/src/reducers/versions.tsx#L618

**Comment by bobsilverberg** [comment] 2020-01-15 17:38
Thanks @mirefly! I'll look into that. The API call should return the hash for the selected file, though, so I'm not exactly sure what's causing this, but I'll look there.

**Comment by mirefly** [comment] 2020-01-15 18:02
@bobsilverberg I know you are already working on this. So I just pasted this quick fix I tried (moving sha256 from `entry` to `VersionFile`), in case it is useful.
<details>

```diff 
diff --git a/src/reducers/versions.tsx b/src/reducers/versions.tsx
index 5b8f874..259bb3b 100644
--- a/src/reducers/versions.tsx
+++ b/src/reducers/versions.tsx
@@ -161,6 +161,7 @@ type InternalVersionFile = {
   created: string;
   downloadURL: string | null;
   id: number;
+  sha256: string | null;
   size: number;
 };
 
@@ -428,14 +429,19 @@ export const getParentFolders = (path: string): string[] => {
   return parents;
 };
 
-export const createInternalVersionFile = (
-  file: ExternalVersionFileWithContent,
-): InternalVersionFile => {
+export const createInternalVersionFile = ({
+  file,
+  path,
+}: {
+  file: ExternalVersionFileWithContent;
+  path: string;
+}): InternalVersionFile => {
   return {
     content: file.content,
     created: file.created,
     downloadURL: file.download_url,
     id: file.id,
+    sha256: file.entries[path] ? file.entries[path].sha256 : null,
     size: file.size,
   };
 };
@@ -615,20 +621,18 @@ export const getVersionFile = (
       return undefined;
     }
 
-    if (!entry.sha256) {
-      _log.debug(
-        `sha256 missing for entry for path: ${path}, versionId: ${versionId}`,
-      );
-      return undefined;
-    }
-
     if (file) {
+      if (!file.sha256) {
+        _log.debug(`sha256 missing for file: ${path}, versionId: ${versionId}`);
+        return undefined;
+      }
+
       return {
         ...file,
         filename: entry.filename,
         mimeType: entry.mimeType,
         path,
-        sha256: entry.sha256,
+        sha256: file.sha256,
         type: entry.type,
         version: version.version,
       };
@@ -1359,7 +1363,7 @@ export const createReducer = ({
             ...state.versionFiles,
             [version.id]: {
               ...state.versionFiles[version.id],
-              [path]: createInternalVersionFile(version.file),
+              [path]: createInternalVersionFile({ file: version.file, path }),
             },
           },
           versionFilesLoading: {

```
</details>

**Comment by bobsilverberg** [comment] 2020-01-15 18:34
Thanks @mirefly. It does seem like the cause of this is that the entry for the file in question is not updated when we call `loadVersionFile`. I like your suggestion, but I think ideally we should keep `entries` up to date, and that would avoid having to carry the `sha256` around in two places. I'm going to see how complicated that would be to do, and if it will also solve the problem.

**Comment by bobsilverberg** [comment] 2020-01-15 19:05
@mirefly I tried my approach, but because we are storing the `entries` internally in an array, it makes it much more complicated. Your approach seems better, and I tried it and it seems to work well. Because this is a P1, we need to land this ASAP. Some tests also need to be updated, and I'll also have to check there aren't any repercussions on the rest of the code.

I don't want to "steal" your patch, so if you think you have time to create a PR for this, including all the test changes (which are minimal), then please go ahead and do so. I don't want to put any pressure on you, though, so if you don't think this is something you can do in the next hour or so, please let me know and I'll create a PR based on your patch, and update all the tests.

**Comment by mirefly** [comment] 2020-01-15 19:30
Thanks @bobsilverberg I created PR #1394

**Closed** 2020-01-15 19:47 UTC
Labels: priority: blocks release, priority: p1

**Comment by ioanarusiczki** [comment] 2020-01-16 10:15
@mirefly I checked this on dev and stage with FF72(Win10) for browse and compare pages using the Network and I do not see lots of API calls.
I navigated using the keyboard shortcuts or clicking on files and it looks good to me. 

An example: 

![API calls](https://user-images.githubusercontent.com/33448286/72516082-c06f8400-3859-11ea-99ab-8639af185684.gif)
