### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] in dev

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1443] opened 2020-02-18 05:24 UTC
In dev, we have the following error when go to http://localhost:3000/. It happened after c0316f414a023411f8ddc94911d86174f064fd53, and has something to do with `react-script`. There are many bug reports like https://github.com/facebook/create-react-app/issues/8490, and probably only  need to upgrade `react-script` to `3.4.0`, hoping [Stroybook can be built on CI](https://github.com/mozilla/addons-code-manager/issues/1430).
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/home/sf/addons-code-manager/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/sf/addons-code-manager/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:317:13)
    at /home/sf/addons-code-manager/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/sf/addons-code-manager/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/sf/addons-code-manager/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:317:13)
    at /home/sf/addons-code-manager/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sf/addons-code-manager/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/home/sf/addons-code-manager/node_modules/react-scripts/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/home/sf/addons-code-manager/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by bobsilverberg** [comment] 2020-02-18 16:16
@mirefly I'm not seeing this error locally with the latest master. We had a problem with `react-scripts 3.3.1`, but I suppose we can try `3.4.0` and maybe that fixes the issue that existed with `3.3.1`. There are a couple of other dependency updates in the PR queue, so we can try applying all of them and see if Storybook is still happy.

**Comment by bobsilverberg** [comment] 2020-02-18 16:39
Odd, after applying https://github.com/mozilla/addons-code-manager/pull/1434 locally I am now seeing that error, but there doesn't seem to be anything in that PR that would have caused such a change. I'll try applying the others and see what happens.

**Comment by mirefly** [comment] 2020-02-18 16:43
The steps I tried are: (on cb64c4c)
1. `git clone` a clean repository
2. run `yarn` then `yarn dev` (Yarn Lock file is changed after running `yarn`)
3. Go to `localhost:3000` and see the error

**Comment by bobsilverberg** [comment] 2020-02-18 17:13
Unfortunately, merging the PR to update `react-scripts` to `3.4.0` broke the Storybook build again. I suppose a working local install is more important at this point than the `storybook-build` task, but this is something we're going to have to deal with. It would be good to see if merging https://github.com/mozilla/addons-code-manager/pull/1442 helps in this case, but it currently has a conflict because of the other renovate PRs that have recently been merged. I'll see if I can manually update that dependency without the renovate PR.

**Comment by bobsilverberg** [comment] 2020-04-17 13:15
It looks like this problem is gone. @mirefly please feel free to reopen if you can still reproduce.

**Closed by bobsilverberg** 2020-04-17 13:15 UTC
