### ISSUE TITLE
Always show compare dropdowns

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#758] opened 2019-05-16 15:24 UTC
In order to switch quickly from browse mode to compare mode or vice versa, we could always show the compare dropdowns, even in browse mode, where the "old" file would just be unselected.

**Edit from @kumar303**: this feature is also crucial to work around https://github.com/mozilla/addons-server/issues/11286 which could be a harder one to fix.

**Comment by kumar303** [comment] 2019-05-29 14:59
Good idea. I was thinking of ways to connect these screens better.

**Comment by kumar303** [comment] 2019-11-27 17:04
At first I was sure that this will be a dupe of https://github.com/mozilla/addons-code-manager/issues/757 but I can now say for sure that it will be.

**Closed by kumar303** 2019-11-27 17:04 UTC
Labels: priority: mvp, priority: p3, state: duplicate, type: feature
