### ISSUE TITLE
Problems with writing reviewer comments 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1607] opened 2020-06-04 11:46 UTC
A new issue should be filed because it was not affected by https://github.com/mozilla/addons-code-manager/issues/1594#issuecomment-638741374

On both dev and stage:

- the client side has problems. If I try to write "test test test" it will only show up "tst tst tst".
- if I hurry to write more text it will cause strange errors, comment cannot be saved, the page I was on is not displayed and another one is available instead.
- if I use `h` in the text it will open and close the side panels. 

![code manager](https://user-images.githubusercontent.com/33448286/83741096-6c2a3c80-a660-11ea-9075-47bfa1f37a2d.gif)

- posting comments through the API is working. 

It's been confirmed this issue is also reproducible on AMO prod.

**Comment by mirefly** [comment] 2020-06-08 00:59
This is caused by the recent release of [`react-textarea-auto` v8.0.0](https://github.com/Andarist/react-textarea-autosize/releases/tag/v8.0.0) which removed the prop `inputRef` we are using.

Simply changing the `inputRef` to `ref` is supposed to work. However, I could not figure out a good way to make TSC happy... The compiler keeps using the declaration file `@types/react-textarea-autosize`. [`yarn remove @types/react-textarea-autosize` ](https://github.com/Andarist/react-textarea-autosize/issues/268#issuecomment-633720705) could not remove that declaration file since we have another package `@storybook/components` still depending on it.

We might want to rollback to `react-textarea-auto` v7 first?

**Comment by bobsilverberg** [comment] 2020-06-08 13:14
Thanks for looking into this @mirefly. 

I agree we should rollback `react-textarea-autosize` to fix this for now, but it seems like we should also look into how we're meant to deal with this. Do we know why they removed the `inputRef` prop in version 8, and what one is supposed to do as a result? Should we open an issue in their repo discussing this to see what they recommend, or if they could perhaps put the prop back, if it's really needed?

**Comment by bobsilverberg** [comment] 2020-06-08 13:49
Fixed via https://github.com/mozilla/addons-code-manager/pull/1614

**Closed by bobsilverberg** 2020-06-08 13:49 UTC
Labels: priority: p2, type: prod_bug

**Comment by mirefly** [comment] 2020-06-08 16:00
> Do we know why they removed the inputRef prop in version 8, and what one is supposed to do as a result?

They are using [`React.forward`](https://reactjs.org/docs/forwarding-refs.html) now, thus we are supposed to use `ref` instead of `inputRef` (there is no need request to put `inputRef` back). We also need to [remove `@types/react-textarea-autosize`](https://github.com/Andarist/react-textarea-autosize/issues/268#issuecomment-633720705), since they have rewritten the package with TS and it does not need Definitely typed anymore, and the declaration file in  DefinitelyTyped is obsolete (for v7).

One extra thing is that we have to wait for [`@storybook/components` ](https://github.com/storybookjs/storybook/blob/master/lib/components/package.json)updating their dependence on `react-textarea-autosize` to v8. Otherwise the obsolete declaration file, in `@types/react-textarea-autosize`, seems to confuse the TS compiler.

The simplest way I guess is just to wait for `@storybook/components` updating their dependencies. @bobsilverberg

**Comment by bobsilverberg** [comment] 2020-06-08 16:05
Thanks for the detailed information, @mirefly, and thanks for the fix! Do you think it's worth filing an issue for `@storybook/components` to request they update their deps?

**Comment by mirefly** [comment] 2020-06-08 16:18
> Do you think it's worth filing an issue for @storybook/components to request they update their deps?
Good idea! I think so.

**Comment by ioanarusiczki** [comment] 2020-06-09 18:25
@bobsilverberg @mirefly 

I could no longer reproduce this issue on AMO dev - FF76(Win10). 

![comments are alright](https://user-images.githubusercontent.com/33448286/84185466-b6178600-aa97-11ea-8874-80448da54877.gif)
