### ISSUE TITLE
An error occurs for add-ons after changing the new/old versions on compare pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1261] opened 2019-11-22 13:58 UTC
Followup for https://github.com/mozilla/addons-code-manager/issues/1235#issuecomment-557268382

STR:
- Load https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688312...1688399/ 
- Select an Old version of `7` and New version of `10.2.3`
- Click on any other file, such as `mozilla-recommendation.json`

![compare616909](https://user-images.githubusercontent.com/33448286/69337012-86726f00-0c68-11ea-9526-0d03036721dc.gif)

The same error is displayed when I choose for https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1510628/ old version `3.3.6` and new version is `5.1.6`

![compare7560](https://user-images.githubusercontent.com/33448286/69337214-0698d480-0c69-11ea-9efa-7339a8c81c95.gif)

**Comment by kumar303** [comment] 2019-11-22 23:16
Here's the error in the first example:

```
Error: "Entry status missing for path: Img/3.24color.bmp, versionId: 1688399"
    c fileTree.tsx:235
    Ot fileTree.tsx:218
    yo index.tsx:328
    Redux 5
    React 13
    r helpers.js:87
```
...which is thrown [here](https://github.com/mozilla/addons-code-manager/blob/a020855373d98bd2dbce6bb94cbc97535c121f18/src/reducers/fileTree.tsx#L235-L237).

It could be that the file tree needs to be rebuilt when switching versions but I'm not sure.

**Comment by mirefly** [comment] 2019-11-25 19:36
Ohhh... We thought only entry status depends on `comparedToVersionId` (so we add `entryStatusMap` in #1025), but it is not true. The deleted path in `version.entries` also depends on `comparedToVersionId`.

**Comment by kumar303** [comment] 2019-11-26 23:20
Heh, yeah. I think the file tree reducer needs to consider `comparedToVersionId` but I'm not totally sure. I only took a quick look at it.

**Comment by mirefly** [comment] 2019-11-27 22:12
>  I think the file tree reducer needs to consider comparedToVersionId

I agree. The problem is the file tree reducer uses `version` object to build file tree, but we have no way to know `comparedToVersionId` of `version`. One approach in my mind is to move `entries` out of `version` object., and create `state.versionEntries.[versionId=?;comparedToVersionId=?]`. I tried this a bit but it looks like a quiet big change. Or just copy out entries as the first step, so that it will not disturb too much? @kumar303  How do you think about it?

**Comment by kumar303** [comment] 2019-11-27 22:29
> The problem is the file tree reducer uses `version` object to build file tree, but we have no way to know `comparedToVersionId` of `version`. 

Is there a way to make `comparedToVersionId` accessible?

> One approach in my mind is to move `entries` out of `version` object., and create `state.versionEntries.[versionId=?;comparedToVersionId=?]`. 

Yeah, that sounds like a big change. Could the file tree state just get something like `comparedToVersionId: number | undefined` (similar to [`forVersionId`](https://github.com/mozilla/addons-code-manager/blob/83eb299a13464e5f25a1bbd47a4fae917eac3f6b/src/reducers/fileTree.tsx#L469)) so that [`getTree()`](https://github.com/mozilla/addons-code-manager/blob/83eb299a13464e5f25a1bbd47a4fae917eac3f6b/src/reducers/fileTree.tsx#L484-L492) will return empty and force the calling component to dispatch `buildTree()` again?

**Comment by mirefly** [comment] 2019-11-27 23:14
>  Could the file tree state just get something like comparedToVersionId: number | undefined (similar to forVersionId) so that getTree() will return empty and force the calling component to dispatch buildTree() again?

I think this should is possible, but the problem is how to know which `version` we should pass to `buildTree({version})`, since `version` is in `state.versionInfo.[versionId]` (or set the loaded version to undefined, and fetch data again?).

**Comment by mirefly** [comment] 2019-11-29 16:57
It is tempting to put `comparedToVersionId` back to `version` object. That should be an easier fix for this issue, but I am not sure if we want it.

**Comment by kumar303** [comment] 2019-12-02 15:59
A quick look suggests that we could add a `comparedToVersionId` param to `fileTree.getTree()` and `fileTree.actions.buildTree()`, which should allow us to use it as a key.

`FileTree` is the only component currently calling those two functions. It maps `tree` to [`getTree()`](https://github.com/mozilla/addons-code-manager/blob/f1ad515225dee0f9783dbdb0d66cf4fa0f9dbdf8/src/components/FileTree/index.tsx#L209) and dispatches [`buildTree()`](https://github.com/mozilla/addons-code-manager/blob/f1ad515225dee0f9783dbdb0d66cf4fa0f9dbdf8/src/components/FileTree/index.tsx#L75) as needed. Since `FileTree` is always rendered by `VersionFileViewer`, then we should be able to pass it a [`comparedToVersionId`](https://github.com/mozilla/addons-code-manager/blob/2e1316294c5a855e7e8fdbe4f783504f3f58b84f/src/components/VersionFileViewer/index.tsx#L26) value

**Comment by kumar303** [comment] 2019-12-04 03:17
Hi @mirefly. This issue has been flagged as higher priority than the others you might have in your queue (I'm thinking of the follow-up issues). Is this something you'd be interested in working on next?

**Comment by mirefly** [comment] 2019-12-04 15:33
>  Is this something you'd be interested in working on next?
Yeah. Let me try this today.

**Closed** 2019-12-07 20:24 UTC
Labels: priority: mvp, priority: p3, type: bug

**Comment by ioanarusiczki** [comment] 2019-12-09 14:58
@mirefly The error is not reproducible anymore for the first example. 
It's still reproducible for https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1510628/
Let me know if the fix is only meant for https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688312...1688399/ and if I should open a separate issue for the one above.
Thanks!

**Comment by mirefly** [comment] 2019-12-09 17:35
Oh.. I did not notice the difference of the two examples.

> Let me know if the fix is only meant for https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688312...1688399/ and if I should open a separate issue for the one above.

Yes, I only fixed the first one. Please file a separate issue for the second one. @ioanarusiczki Thanks for catching this!

**Comment by ioanarusiczki** [comment] 2019-12-10 10:08
@mirefly Ok, I filed it here for further investigation https://github.com/mozilla/addons-code-manager/issues/1327
