### ISSUE TITLE
Minified files with less than 2000 chars should not display the message to show the original file

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1507] opened 2020-03-31 14:26 UTC
Followup for https://github.com/mozilla/addons-code-manager/issues/1462

STR:
1. Load this file https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2FalibabaChina.js
or any file for this add-on which is from ?path=src/conten/engines/

Expected result:
"Show the original diff" or "View the original file" should not be displayed since the entire file is already visible. 

Actual result:
"Show the original diff" or "View the original file" are available. 

Notes:
This is reproducible on browse and compare pages for minified files under 2000 chars on dev - FF74(Win10). 

For QA:

Not only does the patch in #1539 address this issue, but it introduces some other changes discussed below, specifically:

- For non-minified files, trimming is based on number of lines, not number of characters.
- For minified files, trimming is based on number of characters.

**Comment by bobsilverberg** [comment] 2020-03-31 19:09
@wagnerand This issue came up because we have added logic to truncate any files that are identified as minified, which means that the app *does* execute the logic to truncate these files, *but* our general rule for truncation is that we truncate files to 2000 characters. This means a minified file that is 1999 characters will undergo truncation, but won't actually be shortened, because it's below the 2000 character threshold.

I bring this up because I am wondering if we should have a smaller character count for minified files, and only display the first, say, 100 characters, rather than the first 2000. I don't know that we have any evidence that a minified file of 2000 causes any slowness, and if it doesn't then I guess we don't need to add this extra logic, but if it does then it seems like we might as well do "more truncation" on minified files. What are your thoughts on this?

**Comment by wagnerand** [comment] 2020-04-01 10:17
I expected the logic that identified files as being minified to replace our general truncation logic. Could you expand on the motivation having both?

**Comment by bobsilverberg** [comment] 2020-04-01 13:55
> I expected the logic that identified files as being minified to replace our general truncation logic. Could you expand on the motivation having both?

I assumed that there could be large files that are not truncated, isn't that the case? If so, then we need logic to deal with both cases: minified files, and large files.

**Comment by wagnerand** [comment] 2020-04-01 14:22
I guess that would be possible, but from my experience they don't cause much of a performance problem, unless they are *very* large.

If you have examples where we see slowness, I'd be interested to take a look.

For minified files, I think the current limit of 2000 characters is ok, that's not too much text. What I noticed is the file mentioned in the report has much fewer than 2000 characters (391) and so we shouldn't show the the truncation note since nothing was truncated.

For non-minified files, we should probably increase the truncation limit significantly. However, since we now have a metric to detect minified files, the truncation logic should look at number of lines, and truncate if we exceed 5000 lines, to cover huge files.

**Comment by bobsilverberg** [comment] 2020-04-01 14:41
> I guess that would be possible, but from my experience they don't cause much of a performance problem, unless they are _very_ large.
> 
> If you have examples where we see slowness, I'd be interested to take a look.
> 
> For minified files, I think the current limit of 2000 characters is ok, that's not too much text. What I noticed is the file mentioned in the report has much fewer than 2000 characters (391) and so we shouldn't show the the truncation note since nothing was truncated.
> 
> For non-minified files, we should probably increase the truncation limit significantly. However, since we now have a metric to detect minified files, the truncation logic should look at number of lines, and truncate if we exceed 5000 lines, to cover huge files.

Well, @ioanarusiczki did find a couple of instances where files that looked minified were not identified as such (see https://github.com/mozilla/addons-code-manager/issues/1462#issuecomment-606667083), so I'm not sure we want to abandon our code for large files just yet. It seems like a good safety hatch for large files that are not identified as minified. There is already an issue filed to remove the message for a minified file that didn't need to be truncated (https://github.com/mozilla/addons-code-manager/issues/1507).

**Comment by bobsilverberg** [comment] 2020-04-01 15:08
@wagnerand This conversation has made me realize that the code that I added to truncate minified files is actually doing nothing, other than changing the default behaviour for minified files on the compare page from not truncating to truncating. Without a change to the allowed number of characters for minified files, the code does nothing because any files over 2000 chars would have been truncated anyway.

So I do think another change is required. This could be either:
- Truncate minified files a lot more than they are now (e.g., only show 100 chars).
- As you suggest, move away from using a char count to determine whether a file should be truncated to using a line count, and always truncate minfied files.
- Something else?

I hesitate to do the second option because I think that's what we had before, and then changed it to character count, so we're basically undoing all that work.

What do you think?

**Comment by wagnerand** [comment] 2020-04-01 15:47
> I hesitate to do the second option because I think that's what we had before, and then changed it to character count, so we're basically undoing all that work.

I had a sentence about that while drafting the previous comment, but had deleted it before submitting. Let' me expand on it now:

It's correct that's what we had. I think it's also fair to say the results weren't super great.

I believe I mentioned this before in an earlier meeting, as far as I can see looking at code manager pages, neither counting characters nor lines on their own would give us the expected behavior. That's why I had proposed a combination of both, e.g. characters per line.

With the new logic covering minified files specifically, we are addressing a part of this, as far as I understand.

That leaves non-minified files. Now, we can stick to characters, but I think it is less relevant given that we can assume that there is a reasonable amount of characters per line (otherwise it would be considered minified). Following that assumption we could focus on number of lines, since we established that truncation due to overly-long lines would be covered by the new minified-files logic.

If we don't want to move back to line-counts immediately, we could have a guesstimate of about 300-500k characters (assuming ~80-100 characters per line, which is know is more than what an average code would have) times ~5000 lines.

**Comment by bobsilverberg** [comment] 2020-04-01 20:50
Thanks for the feedback, @wagnerand. It sounds like the check for minfied files *should* cover us for the cases where a file is large because it is *wide*, as opposed to *long*, and therefore it does make sense to go back to using number of lines of code as a sign to truncate.

So, let's change the logic to say we truncate files either because they are minified, or if they have more than 5000 lines of code. With this new logic, do we want to make it so that the Compare view truncates all files that match this criteria by default? The current behaviour is that only minified files are truncated by default in the Compare view, and non-minified files and not truncated by default even if they are "too large".

**Comment by wagnerand** [comment] 2020-04-02 10:04
> With this new logic, do we want to make it so that the Compare view truncates all files that match this criteria by default? The current behaviour is that only minified files are truncated by default in the Compare view, and non-minified files and not truncated by default even if they are "too large".

I am not sure whether that's feasible, but ideally, for the compare view, we would make that decision based on the diff-size. I like the github approach for diff/commit views. It focuses on the changes and collapses non-changed lines. Could we do a similar thing here? If the file has a large number of lines, and a reasonably-sized diff, could we truncate (ideally collapse with an option to expand, but probably out of scope for this issue), the parts of the file that are unchanged?

Generally, I am hesitant to truncate in a way that would hide diffs. There is a higher risk to that for reviewers to miss an important change.

what do you think, @bobsilverberg?

**Comment by bobsilverberg** [comment] 2020-04-02 12:55
> > With this new logic, do we want to make it so that the Compare view truncates all files that match this criteria by default? The current behaviour is that only minified files are truncated by default in the Compare view, and non-minified files and not truncated by default even if they are "too large".
> 
> I am not sure whether that's feasible, but ideally, for the compare view, we would make that decision based on the diff-size. I like the github approach for diff/commit views. It focuses on the changes and collapses non-changed lines. Could we do a similar thing here? If the file has a large number of lines, and a reasonably-sized diff, could we truncate (ideally collapse with an option to expand, but probably out of scope for this issue), the parts of the file that are unchanged?
> 

It's possible to implement such a feature, but it would be a pretty big task. I suggest you open a separate issue for that, so that we can track it properly, but I also suggest that it's probably not something we'll get done right away, so let's assume we won't have that anytime soon.

> Generally, I am hesitant to truncate in a way that would hide diffs. There is a higher risk to that for reviewers to miss an important change.
>

I understand. Ok, let's make the change suggested at https://github.com/mozilla/addons-code-manager/issues/1507#issuecomment-607482956, i.e., truncate minified files and those with 5000 or more lines, but keep the current practice of not truncating any non-minified files by default for the Compare view.

Sound good?

**Comment by wagnerand** [comment] 2020-04-02 13:47
That works for me, thank you @bobsilverberg!

**Comment by bobsilverberg** [comment] 2020-04-02 17:10
@wagnerand Just when I thought I was done with questions on this...

With the suggestion above, we will have two different scenarios/methods now:
1. For minified files, truncate them to a particular number of characters. We need to use characters and not lines as minified files often have smaller numbers of very wide lines.
2. For non-minified files, truncate them if they have more than *x* lines (i.e., not chars), and truncate them to a particular number of lines.

What this means is that we have one truncation method for minfied files (based on chars) and one for non-minified files (based on lines).  If we move forward with this (as we decided to do above), I suggest that we reduce the number of displayed chars for minfied files, which should give us at least a bit of a performance improvement for them. It doesn't seem that there's any more value in showing the first 2000 chars of a minified file than simply showing the first 100 chars of a minified file.

Do you agree?

**Comment by wagnerand** [comment] 2020-04-02 18:32
@bobsilverberg Without going into the details, there is value in showing more than just 100. Let's start with 2000 and reduce it if we see noticeable impact on performance.

**Closed** 2020-04-14 19:44 UTC
Labels: component: browse page, component: compare page, priority: p3, type: bug

**Comment by ioanarusiczki** [comment] 2020-04-15 12:44
@bobsilverberg I verified on dev with FF75(Win10) and these are my testing results:
1. For minified files of `.js` type with more than 2000 chars the behavior stays as described here https://github.com/mozilla/addons-code-manager/issues/1462#issuecomment-606612886. 
Minified files such as https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2FauDesign.js which don't have 2000 chars will not display any message and all their content can be viewed.

2. Minified files other than the `.js` such as `json`, `css` or `html` will not look trimmed. But this is being tracked under https://github.com/mozilla/addons-linter/issues/3103

3. For files with a length of 2000+ lines "View the original" is available on Browse pages and the default is "Shorten the diff" in compare view.
The only question is it's 2000 lines or it should be 5000? (seeing the discussions above)

**Comment by bobsilverberg** [comment] 2020-04-15 18:26
> 
> 3. For files with a length of 2000+ lines "View the original" is available on Browse pages and the default is "Shorten the diff" in compare view.
> The only question is it's 2000 lines or it should be 5000? (seeing the discussions above)
> 

Oops, I guess I got the 2000 chars for minfied files conflated with the 5000 lines for non-minified files. I can easily change it to 5000 lines for non-minified files. @wagnerand Can you just confirm the number of lines you want to use to determine when we should trim a non-minified file?

**Comment by wagnerand** [comment] 2020-04-16 17:27
I'd like to go with 5000, we can reduce it if we see performance impact.

**Comment by ioanarusiczki** [comment] 2020-04-22 13:03
@bobsilverberg The file I gave as an example for 2000 lines https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691093/?path=inject%2Findex.js still has the option to be shorter.
Same for 4999 lines https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691090/?allowSlowPages=false&path=inject%2Findex.js

From what I understand it should start from 5000. 

![2000 lines](https://user-images.githubusercontent.com/33448286/79983683-c86e3e00-84b0-11ea-855b-41e079cfb493.gif)

**Comment by bobsilverberg** [comment] 2020-04-22 13:08
> @bobsilverberg The file I gave as an example for 2000 lines [code.addons-dev.allizom.org/en-US/browse/619691/versions/1691093/?path=inject%2Findex.js](https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691093/?path=inject%2Findex.js) still has the option to be shorter.
> Same for 4999 lines [code.addons-dev.allizom.org/en-US/browse/619691/versions/1691090/?allowSlowPages=false&path=inject%2Findex.js](https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691090/?allowSlowPages=false&path=inject%2Findex.js)
> 
> From what I understand it should start from 5000.
> 
> ![2000 lines](https://user-images.githubusercontent.com/33448286/79983683-c86e3e00-84b0-11ea-855b-41e079cfb493.gif)

That hasn't been fixed yet, but I can do a quick patch and a cherry-pick to get it into this week's push, as it's just a one line change.

**Comment by ioanarusiczki** [comment] 2020-04-23 12:05
@bobsilverberg Then I can mark this verified on dev with FF75(Win10) and the changes will continue with https://github.com/mozilla/addons-code-manager/issues/1552 next week.
