### ISSUE TITLE
Make the first 300 chars visible in compare view for minified files

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1567] opened 2020-04-30 08:53 UTC
Followup for https://github.com/mozilla/addons-code-manager/issues/1552

For some reason there are some minified trimmed files which don't show the first 300 chars in compare view. They will only show /* truncated by code-manager */
 The issue is not reproducible for the Browse files.

Examples:
https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?path=src%2Fmanifest.js

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2FauDesign.js

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2Fbaidu.js

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2Fbing.js

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2Fdepositphotos.js

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fmanifest.js

**Comment by bobsilverberg** [comment] 2020-04-30 12:26
@ioanarusiczki Thanks for finding this. I found the cause. Our code was trying to highlight code that had been trimmed, but that was resulting in an empty set of tokens. There is no reason to highlight code that has been trimmed, so a decent fix for this is to simply not highlight code that has been trimmed, in the Compare view.

**Comment by bobsilverberg** [comment] 2020-04-30 12:28
@ioanarusiczki and @wagnerand I have a PR up for this. Do you think this is a big enough bug to cherry-pick for today's push, or can it wait until next week?

**Comment by ioanarusiczki** [comment] 2020-04-30 12:43
@bobsilverberg From my point of view I say it could wait until next week. But @wagnerand should make the call.

**Comment by willdurand** [comment] 2020-04-30 12:45
@ioanarusiczki did you try to look at these files before this week? I am wondering if that is a new bug (regression) or a problem that existed before.

**Comment by ioanarusiczki** [comment] 2020-04-30 12:55
@willdurand I did not mention it in the previous weeks in my test results.
https://github.com/mozilla/addons-code-manager/issues/1462#issuecomment-606612886
https://github.com/mozilla/addons-code-manager/issues/1507#issuecomment-614016094
so I think it is new. 
However, I remember filing a similar issue a while ago, but I remember it was fixed at that time.

**Comment by wagnerand** [comment] 2020-04-30 12:58
I don't think it's urgent enough to cherry-pick.

**Closed** 2020-05-01 11:59 UTC
Labels: component: compare page, priority: p2, type: bug

**Comment by ioanarusiczki** [comment] 2020-05-04 10:54
@bobsilverberg 

The Browse page shows the first 300 chars as being highlighted and the Compare view shows the first 300 chars with highlighting disabled. 

The issue is fixed on dev. Verified with FF75(Win10).
