### ISSUE TITLE
Search for text within the source code of an add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#117] opened 2019-02-01 22:01 UTC
User story:

> As a code reviewer, I want to be able to perform a text search on the source code of an add-on.

**Comment by bobsilverberg** [comment] 2020-04-22 20:50
@wagnerand I think this is now a duplicate of #1343, do you agree?

**Comment by wagnerand** [comment] 2020-04-23 11:58
@bobsilverberg Yep, it sounds like it. Feel free to close whichever you prefer.

**Closed** 2020-04-23 12:08 UTC
Labels: priority: p3, type: feature
