### ISSUE TITLE
The compare page is not loaded if the 'chosen new version' contains only deleted files

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#597] opened 2019-04-16 14:30 UTC
This error might come up when #413 is implemented

**STR:**
1. Try to load the following compare page: https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655557...1655558/ - this should compare versions `1.5` and `1.6`
2. Check the console for errors

**Actual result:**
The compare page is not loaded (you will see only a blank screen). I can see the following error in the console :
`Error: "Could not find parent of entry: _locales/it/messages.json`

**Expected result:**
The compare page should not fail to load

**Notes:**
- looking at the api response for this file comparison, it's evident that in version 1.6 (1655558) the `_locales/it/messages.json` has been indeed deleted:

```
https://addons-dev.allizom.org/api/v4/reviewers/addon/616548/versions/1655557/compare_to/1655558/
```
![image](https://user-images.githubusercontent.com/31961530/56218012-e23e9f00-606c-11e9-8e42-45eac0ef869f.png)

**Comment by kumar303** [comment] 2019-04-18 19:07
I had a hunch that throwing an error here would be helpful one day 🤣 https://github.com/mozilla/addons-code-manager/pull/537#discussion_r272387166

**Comment by kumar303** [comment] 2019-05-20 21:21
This looks like an API bug: https://github.com/mozilla/addons-server/issues/11480

We could workaround it on the frontend but that would be brittle.

**Comment by kumar303** [comment] 2019-05-21 17:08
Now that https://github.com/mozilla/addons-server/issues/11480 has landed, I can no longer reproduce the bug.

**Closed by kumar303** 2019-05-21 17:08 UTC
Labels: component: compare page, needs: api, priority: p3, type: bug

**Comment by AlexandraMoga** [comment] 2019-05-22 09:39
The page at https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655557...1655558/ is loading fine for me as well.

I'm marking the issue as verified fixed on -dev with Fx67, Win10x64
