### ISSUE TITLE
`Network error when attempting to fetch source` message is shown after reloading a compare page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1370] opened 2019-12-23 12:47 UTC
1. Load a compare page such as https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541798...1541798/?path=popup%2Fpopup.js and reload it several times
2. Look at the top left side of the screen
 
Expected result:
page reloads without errors

Actual result: 
Sometimes a `Network error` red message is shown. It disappears quickly from the screen. 

Notes: 
The issue is intermittent on AMO dev and AMO stage with FF71(Win10). To reproduce it, several reloads are required. 
It is reproducible in compare view. I could not reproduce it in Browse view. 

![network error](https://user-images.githubusercontent.com/33448286/71358505-d14a1400-2591-11ea-9b29-18b6a08ae629.gif)

**Comment by mirefly** [comment] 2019-12-23 21:01
It is probably caused by interrupting the page to fetch the next file. If the preloading is finished (or has not started at all), you will not see this "Network error" message when refreshing the page. We might want not to show the error message caused by preloading, but I am not sure.

**Comment by bobsilverberg** [comment] 2020-04-17 13:26
This is a minor annoyance but not really important to fix. WONTFIX

**Closed by bobsilverberg** 2020-04-17 13:26 UTC
Labels: component: compare page, type: bug
