### ISSUE TITLE
Display responsive images

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#712] opened 2019-05-08 19:39 UTC
### Describe the problem and steps to reproduce it:

- Sign in
- View any large image (see https://github.com/mozilla/addons-code-manager/issues/109), e.g. https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2F21Qo5d5r6s78pEaA_LVzwZ8l_JCdZurhJuREAYDHyx0.jpg

### What happened?

The image does not fit on the screen

### What did you expect to happen?

The image should fit on the screen so you can see it

### Anything else we should know?

There are some guides on how to do this: https://www.google.com/search?client=firefox-b-1-d&q=responsive+images

**Comment by willdurand** [comment] 2019-05-08 19:46
Duplicate of https://github.com/mozilla/addons-code-manager/issues/704?

**Comment by AlexandraMoga** [comment] 2019-05-09 06:29
I think @kumar303 makes a good point here, namely, rather than showing only the full picture size in the file viewer, we should give reviewers  the possibility to zoom in and out on an image (similar to what we do in the frontend screenshot viewer)

If the full image size doesn't fit in the frame, then we should add the ability to scroll, as it was pointed in #704 

So, not a duplicate but rather a complementary issue.

**Comment by kumar303** [comment] 2019-05-09 17:50
> Duplicate of #704?

They are separate issues but #704 won't be possible to reproduce after this is fixed.

And, yeah, we could do some fancy zooming but we should probably start by keeping it simple and showing a responsive image. The reviewer could always right-click and view the image on its own.

**Comment by willdurand** [comment] 2019-05-09 20:26
Ah ok, sorry then. Reading #704, my first thought was to make the image responsive to fix the bug..

**Closed** 2019-06-11 16:02 UTC
Labels: component: browse page, priority: p3

**Comment by ioanarusiczki** [comment] 2019-06-13 11:50
@kumar303 I thinks it looks good (collapsing the panels or without).  Scroll bar appears in some cases. (size of the pictures may be even bigger than their name displays)
Here are some examples 
https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.45.jpg
https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.24MB.jpg
https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F4.14%20MB.jpg
https://code.addons-dev.allizom.org/en-US/browse/616900/versions/1688290/?path=Img%2F4.14%20MB.gif
https://code.addons-dev.allizom.org/en-US/browse/616904/versions/1688294/?path=Img%2F3.78.png

**Comment by bobsilverberg** [comment] 2019-06-13 12:27
> @kumar303 I thinks it looks good (collapsing the panels or without). Scroll bar appears in some cases. (size of the pictures may be even bigger than their name displays)
> Here are some examples
> [code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.45.jpg](https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.45.jpg)
> [code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.24MB.jpg](https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F3.24MB.jpg)
> [code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F4.14%20MB.jpg](https://code.addons-dev.allizom.org/en-US/browse/616902/versions/1688292/?path=Img%2F4.14%20MB.jpg)
> [code.addons-dev.allizom.org/en-US/browse/616900/versions/1688290/?path=Img%2F4.14%20MB.gif](https://code.addons-dev.allizom.org/en-US/browse/616900/versions/1688290/?path=Img%2F4.14%20MB.gif)
> [code.addons-dev.allizom.org/en-US/browse/616904/versions/1688294/?path=Img%2F3.78.png](https://code.addons-dev.allizom.org/en-US/browse/616904/versions/1688294/?path=Img%2F3.78.png)

It looks like the issue in these cases is a vertical scroll bar, because the image is too high, not too wide. Our code only deals with too-wide images. Does anyone think we should also be addressing too-high images as well?

**Comment by kumar303** [comment] 2019-06-13 20:09
> Does anyone think we should also be addressing too-high images as well?

I don't think we need to worry about it. It's necessary to preserve the aspect ratio. We could add a *fit on screen* button but the reviewer could just right-click and view the image already.

**Comment by ioanarusiczki** [comment] 2019-06-18 12:29
@kumar303 @bobsilverberg I've done some more testing around images - see how it works with large sizes
and I filed an issue https://github.com/mozilla/addons-code-manager/issues/856

**Comment by kumar303** [comment] 2019-06-19 17:36
@ioanarusiczki Thanks. That looks like a separate issue.
