### ISSUE TITLE
Clicking the overview for cose.sig or mozilla.rsa leads to layout issues in compare view

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#896] opened 2019-07-01 12:54 UTC
STR:
1. I went to 
https://code.addons-dev.allizom.org/en-US/compare/616913/versions/1688316...1688317/?path=META-INF%2Fcose.sig on dev
https://code.addons-dev.allizom.org/en-US/compare/616913/versions/1688316...1688317/?path=META-INF%2Fcose.sig on dev
or 
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474841/?path=META-INF%2Fmozilla.rsa on stage
2. Click in the left panel somewhere on the overview 
3. Observe the page

Expected result:
Page is displayed.

Actual result:
Page won't reload correctly. Stays blank. 

Notes:
Reproducible with FF67 -Win10
Could be related to https://github.com/mozilla/addons-code-manager/issues/402 

![overview click](https://user-images.githubusercontent.com/33448286/60438069-7eae2180-9c18-11e9-8e34-f25f5db6d2df.gif)

**Comment by bobsilverberg** [comment] 2019-07-02 14:51
I've done some investigation into this. My observations are:

The contents of the file `cose.sig` is displayed in browse mode: http://localhost:3000/en-US/compare/616913/versions/1688316...1688317/?path=META-INF/cose.sig

![Screenshot 2019-07-02 10 10 38](https://user-images.githubusercontent.com/142755/60519490-ab624780-9cb1-11e9-80f9-be45134e1336.png)

but not in compare mode: http://localhost:3000/en-US/compare/616913/versions/1688316...1688317/?path=META-INF/cose.sig

![Screenshot 2019-07-02 10 11 14](https://user-images.githubusercontent.com/142755/60519533-bfa64480-9cb1-11e9-945e-2a1f7f5b57c6.png)

yet the Code Overview is shown in both cases. 

The problem seems to stem from the fact that we are not getting any `hunks` in the `diff` property returned by the Compare API for a binary file, but we are getting the `content` of a binary file returned by the Browse API.

When the Code Overview tries to generate an anchor for the link (via [`getCodeLineAnchor`](https://github.com/mozilla/addons-code-manager/blob/99f760e001c95f0866bf9a82e6c275e9f71e006e/src/pages/Compare/utils.tsx#L77)), because there are no `hunks` and therefore no `changes`, it is unable to generate a correct anchor and just sets it to ''. This results in a call to [`document.querySelector('#')`](https://github.com/mozilla/addons-code-manager/blob/99f760e001c95f0866bf9a82e6c275e9f71e006e/src/components/DiffView/index.tsx#L116), which generates a client-side syntax error: `'#' is not a valid selector`, which is what seems to cause the blank page.

**Comment by bobsilverberg** [comment] 2019-07-02 15:09
I opened https://github.com/mozilla/addons-server/issues/11759 to track a possible server-side fix for this.

**Comment by bobsilverberg** [comment] 2019-07-03 19:50
Based on the discussion at https://github.com/mozilla/addons-server/issues/11759, it looks like we've decided that we shouldn't render binary content in either the Browse or Compare views, and therefore also shouldn't render a Code Overview for binary files. The latter change should fix this issue. I opened #909 to track the changes required.

**Comment by ioanarusiczki** [comment] 2019-07-04 07:33
@bobsilverberg That's good to know. I found some more examples for "mime_category": "binary" 
The font folder for https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/ has a couple of files 
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?path=popup%2Ffonts%2Fglyphicons-halflings-regular.woff2
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?path=popup%2Ffonts%2Fglyphicons-halflings-regular.eot

**Comment by wagnerand** [comment] 2019-07-05 15:45
Will this be fixed by #916?

**Comment by AlexandraMoga** [comment] 2019-07-18 08:53
@bobsilverberg I don't think this is an issue just with binary files. I was able to reproduce the `SyntaxError: '#' is not a valid selector` error with any file type. You just need to click on an out of range (blank) area in the Code Overview

**Comment by kumar303** [comment] 2019-11-11 20:59
To fix this issue, we can maybe just disable the code overview for binary files.

**Comment by bobsilverberg** [comment] 2020-11-26 13:24
This appears to be fixed now. I think it was fixed by #917. Can you verify, @ioanarusiczki?

**Comment by ioanarusiczki** [comment] 2020-11-27 15:35
@bobsilverberg Yes, I think so. I don't see a code overview for the mentioned files in Compare view.

**Closed** 2020-11-27 15:35 UTC
Labels: component: compare page, priority: p3, state: verified fixed, type: bug
